apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hs-depl
  labels:
    app: hs-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hs-nginx
  template:
    metadata:
      labels:
        app: hs-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-service
  labels:
    app: hs-nginx
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: hs_nginx