apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb-depl
  labels:
    app: lb_nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lb_nginx
  template:
    metadata:
      labels:
        app: lb_nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
  labels:
    app: lb_nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx


    